#!/usr/bin/env python3
# file: lw-server	B. Moody	14 June 2022
#
# HTTP server for viewing local files using LightWAVE

import argparse
import http.server
import os
import shutil
import sys
import tempfile


def script_dir():
    return os.path.dirname(os.path.realpath(__file__))


def lightwave_server(port):
    server_path = os.path.join(script_dir(), 'physionet/cgi-bin/lightwave')
    server_path = os.path.realpath(server_path)
    if not os.access(server_path, os.X_OK):
        sys.exit('{} not found or not executable'.format(server_path))

    client_path = os.path.join(script_dir(), 'physionet/lw')
    client_path = os.path.realpath(client_path)
    if not os.path.isdir(client_path):
        sys.exit('{} not found'.format(client_path))

    client_dir = 'lw'
    home_page = 'index.html'
    
    os.environ['QUERY_STRING'] = ''

    address = ('127.0.0.1', port)
    handler = http.server.CGIHTTPRequestHandler
    try:
        cls = http.server.ThreadingHTTPServer
    except AttributeError:
        cls = http.server.HTTPServer
    server = cls(address, handler)
    port = server.server_address[1]

    url = 'http://localhost:{}/{}/{}'.format(port, client_dir, home_page)
    print('LightWAVE server running at:\n  {}'.format(url))

    os.chdir('physionet')
    server.serve_forever()


# cgi-bin/lightwave

def main():
    ap = argparse.ArgumentParser()

    ap.add_argument('-P', '--port', type=int, default=7777, metavar='PORT',
                    help='local port number for HTTP server')

    opts = ap.parse_args()
    try:
        lightwave_server(opts.port)
    except KeyboardInterrupt:
        sys.exit(1)

if __name__ == '__main__':
    main()
