#!/usr/bin/env python3
# file: lw-server	B. Moody	14 June 2022
#
# HTTP server for viewing local files using LightWAVE

import argparse
import http.server
import os
import shutil
import sys
import tempfile


def script_dir():
    return os.path.dirname(os.path.realpath(__file__))


def lightwave_server(port):
    server_path = os.path.join(script_dir(), 'physionet/cgi-bin/lightwave')
    server_path = os.path.realpath(server_path)
    if not os.access(server_path, os.X_OK):
        sys.exit('{} not found or not executable'.format(server_path))

    client_path = os.path.join(script_dir(), 'physionet/lw')
    client_path = os.path.realpath(client_path)
    if not os.path.isdir(client_path):
        sys.exit('{} not found'.format(client_path))

    client_dir = 'lw'
    home_page = 'index.html'
    
    os.environ['QUERY_STRING'] = ''

    # Subclass handler to silence browser noise:
    #  - 404 for apple-touch-icon (browser auto-request)
    #  - ConnectionResetError / BrokenPipeError from HTTPS-upgrade probes
    class QuietHandler(http.server.CGIHTTPRequestHandler):
        _SILENT_PATHS = {'/apple-touch-icon.png',
                         '/apple-touch-icon-precomposed.png',
                         '/favicon.ico'}

        def send_error(self, code, message=None, explain=None):
            if code == 404 and self.path in self._SILENT_PATHS:
                self.send_response(204)
                self.end_headers()
                return
            super().send_error(code, message, explain)

        def log_error(self, fmt, *args):
            # suppress 400s from TLS-handshake probes
            if args and str(args[1]) == '400':
                return
            super().log_error(fmt, *args)

    class QuietServer(http.server.ThreadingHTTPServer
                      if hasattr(http.server, 'ThreadingHTTPServer')
                      else http.server.HTTPServer):
        def handle_error(self, request, client_address):
            import sys
            if sys.exc_info()[0] in (ConnectionResetError, BrokenPipeError):
                return
            super().handle_error(request, client_address)

    address = ('127.0.0.1', port)
    server = QuietServer(address, QuietHandler)
    port = server.server_address[1]

    url = 'http://lw:{}/{}'.format(port, client_dir)
    print('LightWAVE server running at:\n {}'.format(url))

    os.chdir('physionet')
    server.serve_forever()


# cgi-bin/lightwave

def main():
    ap = argparse.ArgumentParser()

    ap.add_argument('-P', '--port', type=int, default=7777, metavar='PORT',
                    help='local port number for HTTP server')

    opts = ap.parse_args()
    try:
        lightwave_server(opts.port)
    except KeyboardInterrupt:
        sys.exit(1)

if __name__ == '__main__':
    main()
